version: '3.8'

networks:
  default:

services:
   db:
     image: mysql:5.7
     platform: linux/x86_64
     container_name: conference_security
     ports:
       - 3306:3306
     volumes:
       - "./.data/db:/var/lib/mysql"
     environment:
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: conference_security

   adminer:
     image: adminer
     restart: always
     ports:
       - 8082:8080
       
    